LenselinkAsg3Users/Models/DB.cs
using System.Collections.Generic;

namespace LenselinkAsg3Users.Models
{
    public class DB
    {
        public static List<User> GetUsers()
        {
            List<User> users = new List<User>
            {
                new User
                {
                    ID = 1,
                    NameFirst = "John",
                    NameLast = "Smith",
                    Email = "jsmit@email.com"
                },
                new User
                {
                    ID = 2,
                    NameFirst = "Neo",
                    NameLast = "Anderson",
                    Email = "theone@hotmail.com"
                },
                new User
                {
                    ID = 3,
                    NameFirst = "Bart",
                    NameLast = "Simpson",
                    Email = "eatmyshorts@nunya.biz"
                },
                new User
                {
                    ID = 4,
                    NameFirst = "Homer",
                    NameLast = "Simpson",
                    Email = "hsimpson@springfieldpower.com"
                },
                new User
                {
                    ID = 5,
                    NameFirst = "Mary",
                    NameLast = "Delamater",
                    Email = "mdel@murach.com"
                },
                new User
                {
                    ID = 6,
                    NameFirst = "Zak",
                    NameLast = "Revalcaba",
                    Email = "zrav@murach.com"
                },
                new User
                {
                    ID = 7,
                    NameFirst = "Mark",
                    NameLast = "Zuckerburg",
                    Email = "mark@facemash.com"
                },
                new User
                {
                    ID = 8,
                    NameFirst = "Bill",
                    NameLast = "Gates",
                    Email = "william@microsoft.com"
                },
                new User
                {
                    ID = 9,
                    NameFirst = "Mike",
                    NameLast = "Wazowski",
                    Email = "mwazowski@monsters.org"
                },
                new User
                {
                    ID = 10,
                    NameFirst = "Forrest",
                    NameLast = "Gump",
                    Email = "fgump@bubbagump.com"
                }
            };
            return users;
        }

        public static List<User> GestUsersByLastName(string input)
        {
            List<User> users = DB.GetUsers();
            List<User> results = new List<User>();
            foreach (User u in users)
            {
                if (u.NameLast.ToLower().Contains(input.ToLower()))
                {
                    results.Add(u);
                }
            }
            return results;
        }

        public static User GetUserByID(int id)
        {
            List<User> users = DB.GetUsers();
            foreach (User u in users)
            {
                if (u.ID == id)
                {
                    return u;
                }
            }
            return null;
        }
    }
}

LenselinkAsg3Users/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LenselinkAsg3Users.Models
{
    public class User
    {
        public int ID { get; set; }
        public string NameFirst { get; set; }
        public string NameLast { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }

        public string FullName
        {
            get
            {
                var display = NameFirst + " " + NameLast;
                return display;
            }
        }

        public string Slug => NameFirst.Replace(' ', '-') + NameLast.Replace(' ', '-');
    }
}

LenselinkAsg3Users/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace LenselinkAsg3Users.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

LenselinkAsg3Users/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using LenselinkAsg3Users.Models;
using System;

namespace LenselinkAsg3Users.Controllers
{
    public class UsersController : Controller
    {
        public IActionResult Detail(int id)
        {
            User user = DB.GetUserByID(id);
            return View(user);
        }

        [HttpPost]
        public IActionResult List(string id = "")
        {
            List<User> users;

            if (id.Trim() == "")
            {
                users = DB.GetUsers();
            }
            else
            {
                users = DB.GestUsersByLastName(id);
            }

            return View(users);
        }
    }
}

LenselinkAsg3Users/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1>About Us</h1>

<p>So many names! How many names! There are 10 names right now! I will add more when I connect a real database!</p>

<a asp-action="Index" class="btn btn-primary">Home</a>

LenselinkAsg3Users/Views/Home/Index.cshtml
@{
    ViewBag.Title = "View Users - A Michael Lenselink Production";
}

<h1>Users</h1>

<div class="list-group">
    <form asp-controller="Users" asp-action="List" method="post">
        <input type="submit" value="View All Users" />
    </form>
</div>
<div>
    <form asp-controller="Users" asp-action="List" method="post">
        <p>
            Search by Last Name: <input type="text" name="id" />
            <input type="submit" value="Search" />
        </p>
    </form>
</div>
<div>

    <a asp-controller="Home" asp-action="About">
        About Us
    </a>
</div>

LenselinkAsg3Users/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @RenderBody()
</body>
</html>

LenselinkAsg3Users/Views/Users/Detail.cshtml
@model User
@{
    ViewBag.Title = "Product Detail";
}
<h1>Product Detail</h1>
<table class="table table-bordered table-striped">
    <tr>
        <td>ID</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>@Model.FullName</td>
    </tr>
</table>
<a asp-controller="Home" asp-action="Index"
   class="btn btn-primary">Home</a>

LenselinkAsg3Users/Views/Users/List.cshtml
@model List<User>
@{
    ViewBag.Title = "User List";
}
<h1>Product List</h1>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in @Model)
        {
            <tr>
                <td>@product.FullName</td>
                <td>
                    <a asp-controller="Users" asp-action="Detail"
                       asp-route-id="@product.ID">View</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-controller="Home" asp-action="Index"
   class="btn btn-primary">Home</a>